<?php

namespace ProductBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
